### ISSUE TITLE
Budgets: provider crashes if previously created budget was manually removed from DoiT Console

### ISSUE THREAD

**Issue by haizaar** [doitintl/terraform-provider-doit#7]
Scenario:
* Create a budget using Terraform
* Remove the budget
* Run `terraform plan`

Result: Provider crashes :(

```
Stack trace from the terraform-provider-doit_v0.15.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x7cdda9]

goroutine 2366 [running]:
terraform-provider-doit/internal/provider.budgetToBudgetResourceModel(0xc0001aab00?, 0xc002166a50?, {0x14?, 0xc0006829c0?})
        terraform-provider-doit/internal/provider/budget_resource.go:430 +0x29
terraform-provider-doit/internal/provider.(*budgetResource).Read(0xc00028c8a8, {0xd20340, 0xc001034c00}, {{{{0xd244e8, 0xc0010654a0}, {0xb11360, 0xc0011438f0}}, {0xd259f0, 0xc00181b180}}, 0xc00028c8b8, ...}, ...)
        terraform-provider-doit/internal/provider/budget_resource.go:506 +0x34d
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc000328d00, {0xd20340, 0xc001034c00}, 0xc001034c90, 0xc0019d7578)
        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/fwserver/server_readresource.go:101 +0x617
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc000328d00, {0xd20340?, 0xc001034ab0?}, 0xc001cd0a40)
        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/proto6server/server_readresource.go:55 +0x27b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0002ab0e0, {0xd20340?, 0xc000956e70?}, 0xc001079da0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:787 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xbce100?, 0xc0002ab0e0}, {0xd20340, 0xc000956e70}, 0xc001f8f380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003161e0, {0xd20340, 0xc000956de0}, {0xd24818, 0xc000182d00}, 0xc0012f9d40, 0xc000359f80, 0x1196b48, 0x0)
        google.golang.org/grpc@v1.60.0/server.go:1372 +0xe75
google.golang.org/grpc.(*Server).handleStream(0xc0003161e0, {0xd24818, 0xc000182d00}, 0xc0012f9d40)
        google.golang.org/grpc@v1.60.0/server.go:1783 +0xd51
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.60.0/server.go:1016 +0x68
created by google.golang.org/grpc.(*Server).serveStreams.func2
        google.golang.org/grpc@v1.60.0/server.go:1027 +0x12e

Error: The terraform-provider-doit_v0.15.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by haizaar** [comment]
Works great. Thank you!
